### ISSUE TITLE
Shared Core API (standardise across js-ipfs and js-ipfs-api)

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#110]
Once `js-ipfs` milestone 1 is reached, we will start seeing more applications that will use IPFS and perhaps even depend fully on it in order to work. It is very important that we standardise as most as possible the core-API, so that we save our users from countless upgrading hurdles.

This will also help us identify how IPFS should be used directly. While we are at it, we must update `js-ipfs-api` to expose the same interface, so that apps can exchange between a full node and one accessible through an http-api without a problem.

### TODO list:

- [x] define the core-api spec https://github.com/ipfs/specs/issues/85
- [x] update all of js-ipfs core api calls to follow the spec
- [x] update all of js-ipfs-api core api calls to follow the spec

**Comment by diasdavid** [comment]
The work as started https://github.com/ipfs/interface-ipfs-core :D (really excited about it cause now we have tests!)

**Comment by diasdavid** [comment]
This work has solidified and continues to grow in https://github.com/ipfs/interface-ipfs-core

For notifications on API changes, see: https://github.com/ipfs/interface-ipfs-core/issues/55
