### ISSUE TITLE
js-ipfs-api

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#111]
This issue focus on detailing the improvements we are committing to do for `js-ipfs milestone 1`.

`js-ipfs-api` is the IPFS HTTP-API client library used by js-ipfs cli and a ton of other applications that want to interact with an IPFS node through HTTP (mostly go-ipfs nodes). Currently, for `js-ipfs` we have to use a branch of `js-ipfs-api` since IPFS 0.3.11 and 0.4.0 versions different in how the http-api endpoints work. We want to support 0.4.0 http api spec, which is standardised on https://github.com/ipfs/http-api-spec.

You can find `js-ipfs-api` at https://github.com/ipfs/js-ipfs-api

### TODO list: 

- [x] get https://github.com/ipfs/js-ipfs-api/pull/74 merged. It depends on go-ipfs 0.4.0 being released.
- [x] implement remaining swarm features (https://github.com/ipfs/js-ipfs-api/issues/252)
- [ ] increase code coverage to 100%
- [x] feature GET https://github.com/ipfs/js-ipfs-api/issues/263
- [x] enable circle-ci to run our tests as well
- [x] update release process to the dignified pipeline
- [x] create an examples folder that demonstrates how to:
  - [x] use it with browserify
  - [x] use it with webpack
  - [x] link examples in the README
- [x] ensure that every API call is well documented https://github.com/ipfs/js-ipfs-api/issues/58 (note that the `feat/files-api` has more docs than master

**Comment by diasdavid** [comment]
Updated the list with: https://github.com/ipfs/js-ipfs-api/issues/252

**Comment by diasdavid** [comment]
Just added in `https://github.com/ipfs/js-ipfs-api/issues/263`

**Comment by diasdavid** [comment]
This can be closed now. js-ipfs-api now follows interface-ipfs-core, which makes getting both impl to work together almost seamlessly
