### ISSUE TITLE
js-ipfs-unixfs-engine

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#112]
This issue focus on detailing the improvements we are committing to do for `js-ipfs milestone 1`.

Currently, @nginnever is leading the charge on data-importing + files API. It would be excellent to have a couple of extra hands with the list of tasks below.

https://github.com/ipfs/js-ipfs-data-importing

### TODO list:

- [ ] increase code coverage to 100%
- [x] enable circle-ci
- [x] update release process to the dignified pipeline
- [ ] docs for the API calls
- [ ] docs for the Importing pipeline (ASCII graphs would be great, I recommend monodraw for the http://monodraw.helftone.com)
- [ ] examples
  - [ ] import a dir with files
  - [ ] export a dir with files

**Comment by diasdavid** [comment]
Just missing the documentation segment -> https://github.com/ipfs/js-ipfs-unixfs-engine/issues/28, we can close this now
