### ISSUE TITLE
js-ipfs-unixfs

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#113]
This issue focus on detailing the improvements we are committing to do for `js-ipfs milestone 1`.

`unixfs` is one of the Data Structures that gets mounted on top of the MerkleDAG, it is what enables ipfs to handle files, like adding and getting them to IPFS. Currently this module is pretty close to finished, only requiring a second (or third) pair of eyes to go through the code, increase the code coverage and make sure everything feels right.

https://github.com/ipfs/js-ipfs-unixfs

### TODO list:

- [ ] increase code coverage to 100%
- [x] enable circle-ci
- [x] update release process to the dignified pipeline
- [x] examples
- [x] ensure that every API call is documented https://github.com/ipfs/js-ipfs-api/issues/58 (note that the `feat/files-api` has more docs than master

**Comment by diasdavid** [comment]
On the same lines as https://github.com/ipfs/js-ipfs/issues/121#issuecomment-211435981, closing this one :)
