### ISSUE TITLE
js-ipfs-repo

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#114]
This issue focus on detailing the improvements we are committing to do for `js-ipfs milestone 1`.

`ipfs-repo` is one of the core pieces of `js-ipfs`. It enables js-ipfs to use different storage backends without having to introduce any complex logic for the other IPFS subsystems. Although this module is quite stable at the time, its performance has room for improvement and documentation needs some love.

https://github.com/ipfs/js-ipfs-repo

### TODO list:

- [ ] increase code coverage to 100%
- [x] enable circle-ci
- [x] update release process to the dignified pipeline
- [x] examples
  - using with fs-blob-store
  - using it in the browser with indexedDB-blob-store
- [x] ensure that every API call is documented

### Extra:

- [ ] benchmarks and increase performance

**Comment by diasdavid** [comment]
On the same lines as https://github.com/ipfs/js-ipfs/issues/121#issuecomment-211435981, closing this one :)
