### ISSUE TITLE
js-ipfs-blocks

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#115]
This issue focus on detailing the improvements we are committing to do for `js-ipfs milestone 1.`

`ipfs-blocks` holds the Block data structure and the `block-service`.

https://github.com/ipfs/js-ipfs-blocks

### TODO list:

- [ ] increase code coverage to 100%
- [x] enable circle-ci
- [x] update release process to the dignified pipeline
- [x] examples
  - [x] creating and manipulating a Block
  - [x] using the Block Service
- [x] ensure that every API call is documented

**Comment by diasdavid** [comment]
Closing this one on the same line of https://github.com/ipfs/js-ipfs/issues/121#issuecomment-211435981

**Comment by diasdavid** [comment]
Booom! One more done. Thank you @noffle for finishing this up :)

**Comment by dignifiedquire** [comment]
Soo many issues getting closed :)

**Comment by diasdavid** [comment]
And you can see the bar filling up.

![image](https://cloud.githubusercontent.com/assets/1211152/14654558/378c9dee-0676-11e6-91b9-0377edb79403.png)

It is very satisfying 

progress bars @jbenet ! :D
