### ISSUE TITLE
js-peer-info

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#116]
This issue focus on detailing the improvements we are committing to do for `js-ipfs milestone 1.`

https://github.com/diasdavid/js-peer-info

### TODO list:

- [x] increase code coverage to 100%
- [x] enable circle-ci
- [x] update release process to the dignified pipeline
- [x] examples
  - [x] creating a Peer
- [x] ensure that every API call is documented

**Comment by noffle** [comment]
Does the example in the readme count, or did you have something else in mind?

**Comment by diasdavid** [comment]
It does count :) forgot to tick the box

**Comment by diasdavid** [comment]
Another one that is complete! :D
