### ISSUE TITLE
js-multiaddr

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#120]
This issue focus on detailing the improvements we are committing to do for `js-ipfs milestone 1.`

https://github.com/jbenet/js-multiaddr

### TODO list:

- [x] increase code coverage to 100%
- [ ] enable circle-ci (https://github.com/jbenet/js-multiaddr/issues/17)
- [x] update release process to the dignified pipeline
- [x] ensure that every API call is documented

**Comment by dignifiedquire** [comment]
@diasdavid I talke to @jbenet and as long as this on his account no circleci because their permission handling is so bad. So I think we can close it for now

**Comment by diasdavid** [comment]
This is pretty much done. Thank you @dignifiedquire for checkin in the remaining parts. The last mile is just activating circle ci, but since the config file is already there, we can close this issue.

**Comment by diasdavid** [comment]
@dignifiedquire posted at the same time :)
