### ISSUE TITLE
js-libp2p-swarm

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#122]
This issue focus on detailing the improvements we are committing to do for `js-ipfs milestone 1.`

https://github.com/diasdavid/js-libp2p-swarm

### TODO list:

- [ ] increase code coverage to 100%
- [x] enable circle-ci
- [x] update release process to the dignified pipeline
- [x] ensure that every API call is documented

**Comment by diasdavid** [comment]
Updated the list with https://github.com/diasdavid/js-libp2p-swarm/issues/22 :)

**Comment by diasdavid** [comment]
Closing this one on the same line of https://github.com/ipfs/js-ipfs/issues/121#issuecomment-211435981
