### ISSUE TITLE
js-libp2p-tcp

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#123]
This issue focus on detailing the improvements we are committing to do for `js-ipfs milestone 1.`

https://github.com/diasdavid/js-libp2p-tcp

### TODO list:

- [ ] increase code coverage to 100%
- [x] enable circle-ci
- [x] update release process to the aegir pipeline
- [x] ensure that every API call is documented

**Comment by diasdavid** [comment]
Just missing now the move to `aegir` :)

**Comment by diasdavid** [comment]
One more :D
