### ISSUE TITLE
js-libp2p-spdy

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#124]
This issue focus on detailing the improvements we are committing to do for `js-ipfs milestone 1.`

https://github.com/diasdavid/js-libp2p-spdy

### TODO list:

- [x] increase code coverage to 100%
- [x] enable circle-ci
- [x] update release process to the dignified pipeline
- [x] ensure that every API call is documented

**Comment by diasdavid** [comment]
Another one done! Thank you @JGAntunes for the precious help!
