### ISSUE TITLE
js-libp2p-ipfs

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#125]
This issue focus on detailing the improvements we are committing to do for `js-ipfs milestone 1.`

https://github.com/ipfs/js-libp2p-ipfs

### TODO list:

- [ ] increase code coverage to 100%
- [x] enable circle-ci
- [x] update release process to the dignified pipeline
- [x] examples

**Comment by diasdavid** [comment]
\o/
