### ISSUE TITLE
Feat/pin tracking issue

### ISSUE THREAD

**Issue by JonKrone** [ipfs/js-ipfs#1261]
This is a tracking issue for items needed to complete the pin api.

Parents depend on children:

- [x] ipfs/js-ipfs/pull/1045.
  - [x] ipfs/js-ipfs-api/pull/700 some fixes for how querystring args are passed for streamed files.
    - [x] ipfs/js-ipfs-api/issues/713 @vmx's work to green the ipfs-api CI
- [x] ipfs/interop/pull/15: tests to confirm that go and js pinning behave the same
  - [x] ipfs/js-ipfsd-ctl#212: fixes in-process daemon initialization
    - [x] ipfs/js-ipfsd-ctl/pull/205 @richardschneider's work on remote shutdown should green the CI
