### ISSUE TITLE
IPNS over DNS tracking

### ISSUE THREAD

**Issue by hugomrdias** [ipfs/js-ipfs#2000]
todo:

- [ ] `ipfs dns` should be recursive by default to follow go-ipfs
- [ ] `ipfs resolve` should be recursive and support `/ipns/<fqdn>`
- [ ] `ipfs name resolve` should be recursive and support `/ipns/<fqdn>`
- [ ] implement dns resolver
- [ ] support cid v1 in subdomain ?? /cc @lidel 
- [ ] finish the RFC following https://github.com/ipfs/RFC/compare/rfc/5-ipns-over-dns

Ref:
https://github.com/ipfs/js-ipfs/issues/1918
https://github.com/ipfs/go-ipfs/issues/5287

**Comment by lidel** [comment]
I'm dropping some notes about DNS over HTTPS:
- **Binary** DNS Queries over HTTPS (DoH): https://tools.ietf.org/html/rfc8484
  (same binary payload format as in regular UDP-based DNS, well understood)
  - good primer on how  `application/dns-message` looks on HTTP https://developers.cloudflare.com/1.1.1.1/dns-over-https/wireformat/
  - https://wiki.mozilla.org/Trusted_Recursive_Resolver
    - DoH endpoint used by Firefox: `https://mozilla.cloudflare-dns.com/dns-query`
- Representing DNS Messages in **JSON**: https://tools.ietf.org/html/rfc8427
  AFAIK this fairly young RFC is supported by DNS provided by Google and Cloudflare as `application/dns-json`:
  - https://developers.google.com/speed/public-dns/docs/dns-over-https
  - https://developers.cloudflare.com/1.1.1.1/dns-over-https/json-format/

If I had to pick which one use in our low level libraries, I am leaning towards binary one.
It not only gives us smaller payload sizes but also more servers support it.

**Comment by momack2** [comment]
@hugomrdias - is there a spec for the js client implementation? the go-ipfs team wants to evaluate whether we can add a go client matching that interface in time for IPFS Camp

cc @Stebalien

**Comment by momack2** [comment]
Is there a status update on this? I see the Q3 OKR has a grade of 0.7 - does that mean there is a finalized/implemented spec?

**Comment by daviddias** [comment]
I'm also interested.

**Comment by bmann** [comment]
Great to meet you @hugomrdias. @expede and @dholms are going to take a look at this and help with the spec / give our opinion.

**Comment by achingbrain** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

The missing pieces from this are implemented here: https://github.com/ipfs/helia-ipns/pull/55
