### ISSUE TITLE
⚡️ v0.42.0 RELEASE 🚀

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#2808]
> Bug fixes

# 🗺 What's left for release

- [x] fix: CLI mkdir/touch/write does not support --mtime-nsecs https://github.com/ipfs/js-ipfs/issues/2803
- [x] fix: Remove ky https://github.com/ipfs/js-ipfs/issues/2801
- [x] fix: webui in jsipfs didn't auto set port to 5002 https://github.com/ipfs/js-ipfs/issues/2781
- [x] fix: IPFS Fails to start with nodejs_gc_runs_total has already been registered https://github.com/ipfs/js-ipfs/issues/2019

# 🚢 Estimated shipping date

27th March

# 🔦 Highlights

- Bug fixes

# 🏗 API Changes

- `ipfs.files.stat` would return `hamt-sharded-directory` when statting a HAMT Shard, it now returns `directory` in line with go-IPFS.

# ✅ Release Checklist

- [x] **Stage 0 - Automated Testing**
  - [x] Feature freeze. If any "non-trivial" changes (see the footnotes of [docs/releases.md](https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs/docs/releases.md) for a definition) get added to the release, uncheck all the checkboxes and return to this stage.
  - [x] Automated Testing (already tested in CI) - Ensure that all tests are passing, this includes:
    - [x] unit/functional/integration/e2e
    - [x] interop
    - [x] all the examples run without problems
    - [ ] IPFS application testing
      - [ ] [ipfs-webui](https://github.com/ipfs-shipyard/ipfs-webui)
      - [ ] [ipfs-companion](https://github.com/ipfs-shipyard/ipfs-companion)
      - [ ] [npm-on-ipfs](https://github.com/ipfs-shipyard/npm-on-ipfs)
      - [ ] [peer-base](https://github.com/peer-base/peer-base)
      - [ ] [service-worker-gateway](https://github.com/ipfs-shipyard/service-worker-gateway)
    - [ ] Third party application testing
      - [ ] [ipfs-log](https://github.com/orbitdb/ipfs-log)
      - [ ] [orbit-db](https://github.com/orbitdb/orbit-db)
      - [ ] [sidetree](https://github.com/decentralized-identity/sidetree)
- [x] **Stage 1 - Internal Testing**
  - [x] Documentation
    - [x] Ensure that [README.md](https://github.com/ipfs/js-ipfs/tree/master/README.md) is up to date
      - [x] Install section
      - [x] API calls
      - [x] Packages Listing
  - Network Testing:
    - test lab things - TBD
  - Infrastructure Testing:
    - TBD
- [ ] **Stage 2 - Community Dev Testing**
  - [ ] Reach out to the IPFS _early testers_ listed in [docs/EARLY_TESTERS.md](https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs/docs/EARLY_TESTERS.md) for testing this release (check when no more problems have been reported). If you'd like to be added to this list, please file a PR.
  - [ ] Reach out on IRC for additional early testers.
- [ ] **Stage 3 - Community Prod Testing**
  - [ ] Update [js.ipfs.io](https://js.ipfs.io) examples to use the latest js-ipfs
  - [ ] Invite the IPFS [_early testers_](https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs/docs/EARLY_TESTERS.md) to deploy the release to part of their production infrastructure.
  - [ ] Invite the wider community (link to the release issue):
    - [ ] [discuss.ipfs.io](https://discuss.ipfs.io/c/announcements)
    - [ ] Twitter
    - [ ] IRC
- [x] **Stage 4 - Release**
  - [x] Take a snapshot of everyone that has contributed to this release (including its direct dependencies in IPFS, libp2p, IPLD and multiformats) using [the js-ipfs-contributors module](https://www.npmjs.com/package/js-ipfs-contributors).
  - [x] Publish to npm:
    ```sh
    # In the root of the repo, run the following commands and follow the on-screen prompts:
    npm run reset && npm i
    npm run release
    ```
  - [x] Publish a blog post to [github.com/ipfs/blog](https://github.com/ipfs/blog) (at minimum, a c&p of this release issue with all the highlights, API changes and thank yous)
  - [ ] Broadcasting (link to blog post)
    - [ ] Twitter
    - [ ] IRC
    - [ ] [Reddit](https://reddit.com/r/ipfs)
    - [ ] [discuss.ipfs.io](https://discuss.ipfs.io/c/announcements)
    - [ ] Announce it on the [IPFS Users Mailing List](https://groups.google.com/forum/#!forum/ipfs-users)
  - [ ] Copy release notes to the [GitHub Release description](https://github.com/ipfs/js-ipfs/releases)

# ❤️ Huge thank you to everyone that made this release possible

* [@achingbrain](https://github.com/achingbrain) (149 commits, 44 PRs, 6 issues, 166 comments)
* [@agustinmessina](https://github.com/agustinmessina) (3 comments)
* [@alanshaw](https://github.com/alanshaw) (8 commits, 6 PRs, 1 issue, 12 comments)
* [@alexjc](https://github.com/alexjc) (1 issue, 1 comment)
* [@andrew](https://github.com/andrew) (7 commits, 14 PRs, 1 comment)
* [@aphelionz](https://github.com/aphelionz) (1 PR, 1 issue, 3 comments)
* [@aquiladev](https://github.com/aquiladev) (1 issue)
* [@betamos](https://github.com/betamos) (1 issue)
* [@bluelovers](https://github.com/bluelovers) (2 commits, 8 PRs, 14 issues, 26 comments)
* [@calikevuche](https://github.com/calikevuche) (2 issues, 1 comment)
* [@carsonfarmer](https://github.com/carsonfarmer) (3 comments)
* [@chafey](https://github.com/chafey) (2 commits, 4 PRs, 4 issues, 9 comments)
* [@ChainSafeSystems](https://github.com/ChainSafeSystems) (1 comment)
* [@christopheSeeka](https://github.com/christopheSeeka) (2 issues, 7 comments)
* [@CLAassistant](https://github.com/CLAassistant) (1 comment)
* [@codecov-io](https://github.com/codecov-io) (4 comments)
* [@daviddias](https://github.com/daviddias) (2 commits, 3 PRs, 1 issue, 7 comments)
* [@dirkmc](https://github.com/dirkmc) (1 PR, 5 comments)
* [@Elvenisboy](https://github.com/Elvenisboy) (1 comment)
* [@emclab](https://github.com/emclab) (3 comments)
* [@Gudahtt](https://github.com/Gudahtt) (1 issue)
* [@hacdias](https://github.com/hacdias) (2 commits)
* [@happy-zhangbo](https://github.com/happy-zhangbo) (2 issues, 2 comments)
* [@hazae41](https://github.com/hazae41) (2 issues)
* [@hsanjuan](https://github.com/hsanjuan) (3 comments)
* [@hugomrdias](https://github.com/hugomrdias) (39 commits, 27 PRs, 6 issues, 35 comments)
* [@icidasset](https://github.com/icidasset) (2 issues, 3 comments)
* [@iRyanBell](https://github.com/iRyanBell) (1 PR)
* [@jacobheun](https://github.com/jacobheun) (45 commits, 3 PRs, 3 issues, 36 comments)
* [@Jonybang](https://github.com/Jonybang) (1 issue)
* [@josselinchevalay](https://github.com/josselinchevalay) (1 issue, 4 comments)
* [@jsonsivar](https://github.com/jsonsivar) (2 issues)
* [@kalmi](https://github.com/kalmi) (1 issue, 1 comment)
* [@kanej](https://github.com/kanej) (1 commit, 1 PR, 2 comments)
* [@kawmaiparis](https://github.com/kawmaiparis) (1 issue, 1 comment)
* [@koivunej](https://github.com/koivunej) (1 issue)
* [@kumavis](https://github.com/kumavis) (1 commit, 1 PR, 2 comments)
* [@latenssi](https://github.com/latenssi) (1 issue, 2 comments)
* [@lidel](https://github.com/lidel) (1 PR, 2 issues, 4 comments)
* [@MaduraRaj](https://github.com/MaduraRaj) (1 issue)
* [@MaxGraey](https://github.com/MaxGraey) (1 comment)
* [@mcclure](https://github.com/mcclure) (1 issue)
* [@mell-old](https://github.com/mell-old) (1 issue)
* [@mfsoftworks](https://github.com/mfsoftworks) (1 comment)
* [@mikeal](https://github.com/mikeal) (1 issue, 12 comments)
* [@mkg20001](https://github.com/mkg20001) (4 commits, 1 issue, 4 comments)
* [@mmm8955405](https://github.com/mmm8955405) (1 issue, 6 comments)
* [@MonarthS](https://github.com/MonarthS) (1 comment)
* [@mpetrunic](https://github.com/mpetrunic) (1 PR)
* [@nijynot](https://github.com/nijynot) (1 commit)
* [@notsag-dev](https://github.com/notsag-dev) (1 PR)
* [@npfoss](https://github.com/npfoss) (1 commit)
* [@obo20](https://github.com/obo20) (1 issue, 3 comments)
* [@olizilla](https://github.com/olizilla) (1 commit, 1 PR, 2 comments)
* [@ottodevs](https://github.com/ottodevs) (5 comments)
* [@pcowgill](https://github.com/pcowgill) (2 PRs, 8 issues, 43 comments)
* [@ribasushi](https://github.com/ribasushi) (1 issue, 1 comment)
* [@rigwild](https://github.com/rigwild) (1 comment)
* [@robertkiel](https://github.com/robertkiel) (6 commits, 6 PRs, 1 comment)
* [@rvagg](https://github.com/rvagg) (1 PR, 7 comments)
* [@SahidMiller](https://github.com/SahidMiller) (1 comment)
* [@sbhamad](https://github.com/sbhamad) (1 issue)
* [@Schwartz10](https://github.com/Schwartz10) (1 comment)
* [@sebastiendan](https://github.com/sebastiendan) (2 issues, 9 comments)
* [@SignpostMarv](https://github.com/SignpostMarv) (2 issues, 2 comments)
* [@siman](https://github.com/siman) (2 comments)
* [@sinkuu](https://github.com/sinkuu) (1 comment)
* [@stale](undefined) (1 comment)
* [@Stebalien](https://github.com/Stebalien) (2 commits, 2 PRs, 1 issue, 9 comments)
* [@svdo](https://github.com/svdo) (1 PR, 1 comment)
* [@tabcat](https://github.com/tabcat) (2 commits, 2 PRs, 1 issue)
* [@tniessen](https://github.com/tniessen) (1 issue)
* [@tuyennhv](https://github.com/tuyennhv) (1 PR, 1 comment)
* [@uchetron](https://github.com/uchetron) (1 issue)
* [@ulvus](https://github.com/ulvus) (1 comment)
* [@vasco-santos](https://github.com/vasco-santos) (72 commits, 17 PRs, 17 issues, 78 comments)
* [@vaultec81](https://github.com/vaultec81) (2 issues, 10 comments)
* [@vmx](https://github.com/vmx) (12 commits, 9 PRs, 11 comments)
* [@warpfork](https://github.com/warpfork) (1 comment)
* [@wemeetagain](https://github.com/wemeetagain) (1 commit, 1 comment)
* [@whyrusleeping](https://github.com/whyrusleeping) (1 comment)
* [@wolfgang](https://github.com/wolfgang) (1 comment)
* [@woss](https://github.com/woss) (1 comment)
* [@x5engine](https://github.com/x5engine) (1 comment)
* [@Xmader](https://github.com/Xmader) (1 commit, 1 PR)
* [@xmaysonnave](https://github.com/xmaysonnave) (1 issue, 1 comment)
* [@zebateira](https://github.com/zebateira) (1 PR)
* [@zot](https://github.com/zot) (1 comment)

# 🙌🏽 Want to contribute?

Would you like to contribute to the IPFS project and don't know how? Well, there are a few places you can get started:

- Check the issues with the `help wanted` label in the [js-ipfs repo](https://github.com/ipfs/js-ipfs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)
- Join an IPFS All Hands, introduce yourself and let us know where you would like to contribute - https://github.com/ipfs/team-mgmt/#weekly-ipfs-all-hands
- Hack with IPFS and show us what you made! The All Hands call is also the perfect venue for demos, join in and show us what you built
- Join the discussion at https://discuss.ipfs.io/ and help users finding their answers.
- Join the [🚀 IPFS Core Implementations Weekly Sync 🛰](https://github.com/ipfs/team-mgmt/issues/992) and be part of the action!

# ⁉️ Do you have questions?

The best place to ask your questions about IPFS, how it works and what you can do with it is at [discuss.ipfs.io](https://discuss.ipfs.io). We are also available at the `#ipfs` channel on Freenode.

**Comment by ulvus** [comment]
Stage 2
"cite" Reach out to the IPFS early testers listed in docs/EARLY_TESTERS.md for testing this release (check when no more problems have been reported). If you'd like to be added to this list, please file a PR."
docs/EARLY_TESTERS.md go to 404

**Comment by achingbrain** [comment]
Nice catch, thanks - I've updated the links, they should point to the right places now.

**Comment by pcowgill** [comment]
When `0.42.0` of `ipfs` is released, is that when `42.0.1` of `ipfs-http-client` will be released? In other words, will releases be synchronized using `lerna` now? Will the versioning remain distinct between the child packages of this monorepo?

**Comment by achingbrain** [comment]
Releases will most likely be synchronised but really it depends what needs to be released and when.

We're also now publishing RCs on every green build of master, so you can get the latest & greatest by installing `ipfs@next` or `ipfs-http-client@next`, etc.

The versions will follow semver (as much as possible) using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/), so they'll remain distinct and (hopefully) indicate the disruption a user will encounter on upgrading.

I want to get us to a point where we have steady, predictable releases, at least monthly or preferably completely automated, but please be patient with us while we're working out the kinks.
