### ISSUE TITLE
Buffer@6.x.x has caused the http client bundle size to increase

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#3604]
There was a new semver major Buffer release which has caused lots of duplication in the browser bundles, particularly the http client.

This should be resolved before the next release.

Instances of

```
./node_modules/borc/node_modules/buffer
./node_modules/it-ws/node_modules/buffer
./node_modules/it-buffer/node_modules/buffer
./node_modules/bl/node_modules/buffer
./node_modules/abstract-leveldown/node_modules/buffer
./node_modules/it-to-stream/node_modules/buffer
./node_modules/iso-random-stream/node_modules/buffer
./node_modules/it-length-prefixed/node_modules/buffer
./node_modules/level-js/node_modules/buffer
./node_modules/it-tar/node_modules/buffer
./node_modules/it-multipart/node_modules/buffer
./node_modules/it-goodbye/node_modules/buffer
./node_modules/level-codec/node_modules/buffer
./node_modules/it-to-buffer/node_modules/buffer
./node_modules/buffer
```

PRs:

- [ ] https://github.com/Level/codec/pull/62
- [x] https://github.com/alanshaw/it-goodbye/pull/4
- [ ] https://github.com/Level/level-js/pull/210
- [x] https://github.com/alanshaw/it-length-prefixed/pull/12
- [ ] https://github.com/hugomrdias/iso-random-stream/pull/54
- [x] https://github.com/alanshaw/it-to-stream/pull/8
- [ ] https://github.com/Level/abstract-leveldown/pull/373
- [ ] https://github.com/rvagg/bl/pull/102
- [x] https://github.com/alanshaw/it-tar/pull/3
- [x] https://github.com/libp2p/js-libp2p-websockets/pull/123

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

It looks like all the PRs were merged and this should not be an issue with the latest js-ipfs packages.
