### ISSUE TITLE
config

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#49]
#### To learn more about config, you can

- try out the ipfs config command with a go-ipfs daemon
- check the config http-api-spec https://github.com/ipfs/http-api-spec/pull/29

#### Implementation Roadmap

- [x] jsipfs config           - Gets or sets the value of a given key of the config file.
  - [x] core
  - [x] http-api (#72)
  - [x] cli
- [x] jsipfs config show           - Outputs the content of the config file.
  - [x] core
  - [x] http-api (#74)
  - [x] cli
- [x] jsipfs config edit           - Opens the config file for editing in $EDITOR.
  - [x] cli (#77)
- [x] jsipfs config replace <file> - Replaces the config with <file>.
  - [x] core
  - [x] http-api (#75)
  - [x] cli

**Comment by diasdavid** [comment]
config http-api spec - https://github.com/ipfs/http-api-spec/pull/29

**Comment by RichardLitt** [comment]
Let me know if the spec needs updating.

**Comment by diasdavid** [comment]
**updated this issue**

**Comment by xicombd** [comment]
@diasdavid I was looking into `jsipfs config edit` but couldn't find any way of accessing the repo's path. 
Should we expose it on `js-ipfs-repo` or did I miss something?

**Comment by diasdavid** [comment]
@xicombd note that the jsipfs cli might be working through the network, so essentially the way to do it is to fetch the config, open it on a editor and when on save, write it back.

**Comment by xicombd** [comment]
Ahhh, makes sense. Thanks for the clarification!

**Comment by xicombd** [comment]
[I'm implementing the `/config/replace` api endpoint](https://github.com/ipfs/js-ipfs/compare/feature/http-api-config-show...feature/http-api-config-replace), but although it works fine with the [spec's curl example](https://github.com/ipfs/http-api-spec/blob/feature/config/apiary.apib#L1822), and the [hapi tests](https://github.com/ipfs/js-ipfs/compare/feature/http-api-config-show...feature/http-api-config-replace#diff-f49865942c96b3480f2f3b11810845caR191), I'm not being able to use it with [js-ipfs-api](https://github.com/ipfs/js-ipfs-api).

I'm calling it like this ([see the test](https://github.com/ipfs/js-ipfs/compare/feature/http-api-config-show...feature/http-api-config-replace#diff-f49865942c96b3480f2f3b11810845caR316)):         
```javascript
const file = 'tests/otherconfig'
ctl.config.replace(file, (err, res) => {
  console.log(err, res)
})
```
And hapi is replying with: 
```javascript
 { statusCode: 400, error: 'Bad Request', message: 'Invalid multipart payload format' }
```

@diasdavid @dignifiedquire do you have any idea how to make this support `js-ipfs-api`? Or should we change `js-ipfs-api` instead, and send the files in another way?

Thanks!

**Comment by diasdavid** [comment]
"multipart strikes again™"

@xicombd good catch, we certainly need to document that, the reality is that go-ipfs uses a custom made Multipart message format which hapijs is rejecting since it expects something with the format of the spec. This might require some hackery in order to get the same Multipart parser that we have in Go.

A way to get this done is

- 1. capture a multipart message for file and one for a dir created by go-ipfs cli or js-ipfs-api
- 2. built the same custom js parser for that custom multipart message, as we have in go-ipfs (https://github.com/ipfs/go-ipfs/tree/master/commands)
- 3. integrate it with hapijs

**Comment by diasdavid** [comment]
https://public.etherpad-mozilla.org/p/multipart-madness

### js-ipfs hacking

```
const multipart = require('ipfs-multipart')

server.route({
     method: ‘POST’
     path: '/files/add'
handler: (req, res) => {
     req.pipe(multipart.parser)
          .on(‘file’, (filename, filestream) => {
          // filename is the entire filepath
                }) 
                .on(‘err’, (err) => {
                
                 })
 }
})
```

#### TODO
- [ ] fork hapi and add option to skip the payload read/parse for a route for a given route
- [ ] make PEZ understand our multipart messages

#### NOTES

Hapi passes the request.raw.req here https://github.com/hapijs/subtext/blob/master/lib/index.js#L296 to `subtext`, that pipes it to `pez` here: https://github.com/hapijs/subtext/blob/master/lib/index.js#L429

**Comment by xicombd** [comment]
Started implementing a multipart parser for ipfs here: https://github.com/xicombd/ipfs-multipart
