### ISSUE TITLE
track: floodsub

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#580]
> I've created this issue to track the development of the floodsub API inside the JS libraries, getting the people interested to rail in quickly and also to give a venue to sync for the ones working on the endeavour.

### Important links

- API discussion - https://github.com/ipfs/js-ipfs/issues/530
- js-ipfs floodsub PR - https://github.com/ipfs/js-ipfs/pull/531/files
- js-ipfs-api floodsub PR - https://github.com/ipfs/js-ipfs-api/pull/377
- floodsub design notes - https://github.com/libp2p/pubsub-notes
- pubsub research group - https://github.com/libp2p/pubsub
- floodsub JS implementation - https://github.com/libp2p/js-libp2p-floodsub
- floodsub testnet - https://github.com/gavinmcdermott/js-libp2p-pstn

### Milestones

- [x] Design and agree on a FloodSub Interface
- [ ] Get first implementation in
- [ ] Apply pubsub testnet to get real data from the implementation.

**Comment by diasdavid** [comment]
##### Lead

@gavinmcdermott is leading the charge of getting js-libp2p-floodsub integrated into js-ipfs and with that come up with an API that works for a scenario where floodsub is 'in process'(js-ipfs) or 'remote' (js-ipfs-api/through http).

**Comment by diasdavid** [comment]
### Testing floodsub interop

Currently, we have interop between go and js. One way to level that up is to grab the floodsub-testnet work and attach it to js-ipfs nodes instead, since js-ipfs and js-ipfs-api share the same API, we can make the testnet code spawn both types of nodes and see how the network behaves :)

**Comment by diasdavid** [comment]
### API design considerations

- API should enable the user cancel a subscription (a not only by killing the process or closing the tab as it happens if js-ipfs-api is used right now)
- floodsub API should enable the developers to not be target of spam attacks - support for TopicDescriptios - https://github.com/libp2p/pubsub-notes/blob/master/flooding/flooding.proto#L22-L49

**Comment by haadcode** [comment]
@diasdavid can we keep the API discussion in the original issue so that we don't have a gazillion places to look for? 

The original discussion is here: https://github.com/ipfs/js-ipfs/issues/530.

> API should enable the user cancel a subscription

This was added to the spec today, `ipfs.pubsub.unsubscribe("topic")`

> floodsub API should enable the developers to not be target of spam attacks - support for TopicDescriptios

There's comments regarding this in the issue above. Let's continue there.

**Comment by haadcode** [comment]
To make sure information gets passed around: I'm working on refactoring the current js-ipfs-api PR and that work is here: https://github.com/haadcode/js-ipfs-api/blob/fix/pubsub/src/api/pubsub.js and tests are here https://github.com/haadcode/js-ipfs-api/blob/fix/pubsub/test/ipfs-api/pubsub.spec.js.

**Comment by haadcode** [comment]
There's also work that needs to happen on go-ipfs side in order to land js-ipfs-api, mainly this: https://github.com/ipfs/go-ipfs/issues/3304

**Comment by haadcode** [comment]
There's a new PR for js-ipfs from @gavinmcdermott here https://github.com/ipfs/js-ipfs/pull/610 (posting here to keep track of all the work that's happening)

**Comment by diasdavid** [comment]
@haadcode @gavinmcdermott, I've updated https://github.com/libp2p/js-libp2p to the latests libp2p versions, so that you don't have to go through it yourselves. All you should have to do is update the version :)

**Comment by haadcode** [comment]
Tests for the pubsub interface are now in a PR in interface-ipfs-core: https://github.com/ipfs/interface-ipfs-core/pull/101

**Comment by haadcode** [comment]
For js-ipfs-api, before merging pubsub, we need this to be merged: https://github.com/ipfs/go-ipfs-dep/pull/13#discussion_r90838240 and have go-ipfs-dep 0.4.5-something released (I've been publishing @haad/go-ipfs-dep v0.4.5-beta.x).

**Comment by gavinmcdermott** [comment]
@haadcode and @diasdavid - Thanks for the updates here. I'm getting caught back up today and will be back in SF late tonight. That said, I'll be available to wrap up work on outstanding items this week!

**Comment by diasdavid** [comment]
- [x] floodsub tests and spec https://github.com/ipfs/interface-ipfs-core/pull/101
- [ ] PR on js-ipfs-api https://github.com/ipfs/js-ipfs-api/pull/471 
- [ ] PR on js-ipfs https://github.com/ipfs/js-ipfs/pull/610
